#include "pch.h"
#include <d3dx11.h>
#include <vostok/render/core/macros_extensions.h>

pcstr make_d3d11_error_string( HRESULT error_code )
{
	switch ( error_code )
	{
		case D3D11_ERROR_FILE_NOT_FOUND:					return "D3D11_ERROR_FILE_NOT_FOUND";
		case D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS:		return "D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS";
		case D3DERR_INVALIDCALL:							return "D3DERR_INVALIDCALL";
		case D3DERR_WASSTILLDRAWING:						return "D3DERR_WASSTILLDRAWING";
		case E_FAIL:										return "E_FAIL";
		case E_INVALIDARG:									return "E_INVALIDARG";
		case E_OUTOFMEMORY:									return "E_OUTOFMEMORY";
		case E_NOINTERFACE:									return "E_NOINTERFACE";
		case DXGI_ERROR_INVALID_CALL:						return "DXGI_ERROR_INVALID_CALL";
		case DXGI_ERROR_NOT_FOUND:							return "DXGI_ERROR_NOT_FOUND";
		case DXGI_ERROR_NOT_CURRENTLY_AVAILABLE:			return "DXGI_ERROR_NOT_CURRENTLY_AVAILABLE";
		case DXGI_STATUS_MODE_CHANGE_IN_PROGRESS:			return "DXGI_STATUS_MODE_CHANGE_IN_PROGRESS";
		case DXGI_STATUS_OCCLUDED:							return "DXGI_STATUS_OCCLUDED";
		case DXGI_STATUS_CLIPPED:							return "DXGI_STATUS_CLIPPED";
		case DXGI_STATUS_NO_REDIRECTION:					return "DXGI_STATUS_NO_REDIRECTION";
		case DXGI_STATUS_NO_DESKTOP_ACCESS:					return "DXGI_STATUS_NO_DESKTOP_ACCESS";
		case DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE:		return "DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE";
		case DXGI_STATUS_MODE_CHANGED:						return "DXGI_STATUS_MODE_CHANGED";
		case DXGI_ERROR_MORE_DATA:							return "DXGI_ERROR_MORE_DATA";
		case DXGI_ERROR_UNSUPPORTED:						return "DXGI_ERROR_UNSUPPORTED";
		case DXGI_ERROR_DEVICE_REMOVED:						return "DXGI_ERROR_DEVICE_REMOVED";
		case DXGI_ERROR_DEVICE_HUNG:						return "DXGI_ERROR_DEVICE_HUNG";
		case DXGI_ERROR_DEVICE_RESET:						return "DXGI_ERROR_DEVICE_RESET";
		case DXGI_ERROR_WAS_STILL_DRAWING:					return "DXGI_ERROR_WAS_STILL_DRAWING";
		case DXGI_ERROR_FRAME_STATISTICS_DISJOINT:			return "DXGI_ERROR_FRAME_STATISTICS_DISJOINT";
		case DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE:		return "DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE";
		case DXGI_ERROR_DRIVER_INTERNAL_ERROR:				return "DXGI_ERROR_DRIVER_INTERNAL_ERROR";
		case DXGI_ERROR_NONEXCLUSIVE:						return "DXGI_ERROR_NONEXCLUSIVE";
		case DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED:			return "DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED";
		case DXGI_ERROR_REMOTE_OUTOFMEMORY:					return "DXGI_ERROR_REMOTE_OUTOFMEMORY";
	}

	return "UNKNOWN D3D11 ERROR";
}
