// $DEFINES$: CONFIG_TDIFFUSE, CONFIG_TNORMAL, CONFIG_PARALLAX, CONFIG_TRANSLUCENCY

#ifndef	VSF_COPY_TC_H
#define VSF_COPY_TC_H

#if CONFIG_TDIFFUSE || CONFIG_TNORMAL || CONFIG_PARALLAX || CONFIG_TRANSLUCENCY
#	define V_PARAM_TC0		1
#	define V2P_PARAM_TC0	1
#endif // #if CONFIG_TDIFFUSE || CONFIG_TNORMAL || CONFIG_PARALLAX || CONFIG_TRANSLUCENCY

void vsf_copy_tc( in v_common input, inout v2p_common output)
{
	if ( CONFIG_TDIFFUSE || CONFIG_TNORMAL || CONFIG_PARALLAX || CONFIG_TRANSLUCENCY)
		output.tc 	 = input.tc;
}

#endif // VSF_COPY_TC_H
