[package]
name = "pdb-parser"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.41", features = ["derive", "env"] }

pdb = { package = "pdb2", git = "https://github.com/afranchuk/pdb", rev = "384c165" }
pdb-addr2line = { git = "https://github.com/srp-survarium/pdb-addr2line", rev = "9fbc537159d8dc5828e3fceaebd2a1c65988b45d" }
pdb-addr2line-orig = { package = "pdb-addr2line", version = "0.11.2" }

bitflags = "2.9.2"
chrono = "0.4.42"

[lints]
workspace = true
