"""match_state - the committed matching ledger, one text row per function.

Replaces the committed `match.db` blob. SQLite re-serialises pages on write, so
git cannot delta it: every matching commit stored a fresh ~4 MB blob (1,333 of
them, ~3.5 GB of history). A flat TSV deltas per line - ~20 KB per commit.

  docs/binary_matching/match_state.tsv    committed truth (this module)
  binaries/match.db                       gitignored query/derivation cache

The derived roster (symbols, pairs, per-statement classification, cross-name
aliases) is a pure function of `report.json` + the rich indexes and is rebuilt
by `match_db.regen()` on every build. Only the columns below survive a rebuild
and cannot be recomputed - they are the matching campaign's memory.

Percentage semantics (gruntz naming; see docs in ~/Projects/surv/):

  cur   fuzzy % in THIS build. Noisy under LTCG/ICF - a function can move
        without its source moving.
  max   peak for THIS source body (`hash`). Resets only when `hash` changes,
        because a rewritten body must prove itself again. The campaign goal is
        to drive every `max` to 100, then take one final simultaneous pass.
  hist  all-time peak. NEVER resets. `hist > max` means we scored better once
        and lost it - a worklist row, and the safety net that makes a wrong
        `max` reset harmless.

`hash` is the function's own source body only (12 hex chars). It deliberately
does NOT include module/TU context: the old `effective_hash` folded in the
owning module's headers and the whole owning .cpp, so editing any sibling
function in a TU reset `max` for every function in it. That left 16,659 of
16,661 rows with max == cur - a 16 MB duplicate of a 0.07 MB column. Context
belongs in the diagnosis, not in the gate.
"""

import csv
import os
import sys

from vostok.core import paths

VOSTOK = str(paths.REPO)
STATE_PATH = str(paths.MATCH_STATE)

# Column order is the file format; keep it stable so diffs stay readable.
COLUMNS = [
    "mangled",   # identity (the demangled form is derived, never stored)
    "unit",      # owning TU id into the [units] legend; a matcher owns a whole TU
    "module",    # logical owner, resolved through unit->module overrides
    "status",    # done | inprogress | blocked | parked
    "cls",       # MATCH | SIZE | QUANTITY | SPLIT  (structure verdict)
    "cur",       # this build
    "max",       # peak for this `hash`
    "hist",      # all-time peak, never resets
    "tries",     # times the source body changed under us
    "size",      # target byte size - the report headline is byte-weighted
    "flags",     # 'f' = frameless (LTCG-customised leaf; queue skips these)
    "hash",      # 12 hex chars of the function's own source body
    "note",      # what was attempted / why parked or blocked - keep it short
]

EXACT = 99.995  # objdiff reports byte-exact as >= this

HEADER = """\
# vostok matching ledger - generated by vostok.ledger.store. DO NOT hand-edit.
#   one row per target function; the derived roster is rebuilt from report.json
#
#   cur    fuzzy % in this build (noisy under LTCG/ICF)
#   max    peak for THIS source body (`hash`); resets only when `hash` changes.
#          Campaign goal: drive every max to 100.
#   hist   all-time peak; NEVER resets. hist > max = we had it better once.
#   tries  times the source body changed under us (high = hard to match)
#   hash   12 hex chars of the function's own source body. Module/TU context is
#          deliberately excluded - it is diagnosis, not a gate.
#   cls    MATCH (statements identical) | SIZE (same count+geometry, bytes
#          differ) | QUANTITY (counts differ) | SPLIT (counts equal, unpairable)
#   status done (max>=100) | inprogress | blocked (something missing) |
#          parked (failed to raise it further)
"""


def _fmt(value):
    """Render a cell: trim floats, blank for None, never emit a tab/newline."""
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".")
    return str(value).replace("\t", " ").replace("\n", " ").replace("\r", "")


def _num(text):
    if text in (None, ""):
        return None
    try:
        return float(text)
    except ValueError:
        return None


UNIT_LEGEND = "# [units] "


def load(path=STATE_PATH):
    """Read the ledger into {mangled: row-dict}.

    `unit` is stored as an id into the `# [units]` legend to keep the 45-char
    TU paths out of all 19k rows; it is resolved back to the path here, so
    callers never see the encoding.
    """
    rows = {}
    if not os.path.exists(path):
        return rows
    units = {}
    with open(path, encoding="utf-8", newline="") as fh:
        body = []
        for line in fh:
            if line.startswith(UNIT_LEGEND):
                ident, _, name = line[len(UNIT_LEGEND):].strip().partition("\t")
                units[ident] = name
            elif not line.startswith("#"):
                body.append(line)
        for rec in csv.DictReader(body, delimiter="\t"):
            mangled = rec.get("mangled")
            if not mangled:
                continue
            for key in ("cur", "max", "hist"):
                rec[key] = _num(rec.get(key))
            rec["tries"] = int(rec["tries"]) if rec.get("tries") else 0
            rec["size"] = int(rec["size"]) if rec.get("size") else 0
            rec["unit"] = units.get(rec.get("unit", ""), "")
            rows[mangled] = rec
    return rows


def save(rows, path=STATE_PATH):
    """Write the ledger deterministically: sorted, LF endings, stable columns."""
    ordered = sorted(rows.values(), key=lambda r: r["mangled"])
    names = sorted({r.get("unit") or "" for r in ordered} - {""})
    ids = {name: str(i) for i, name in enumerate(names)}
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER)
        for name in names:
            fh.write(f"{UNIT_LEGEND}{ids[name]}\t{name}\n")
        writer = csv.writer(fh, delimiter="\t", lineterminator="\n")
        writer.writerow(COLUMNS)
        for row in ordered:
            cells = []
            for col in COLUMNS:
                value = ids.get(row.get("unit"), "") if col == "unit" else row.get(col)
                cells.append(_fmt(value))
            writer.writerow(cells)
    os.replace(tmp, path)
    return len(ordered)


def status_for(row, flagged=False, paired=True):
    """done > parked > blocked > inprogress, in that precedence."""
    if (row.get("max") or 0) >= EXACT:
        return "done"
    if flagged:
        return "parked"
    if not paired:
        return "blocked"
    return "inprogress"


def advance(previous, mangled, *, module, cur, cls, body_hash, paired=True,
            flagged=False, note=None):
    """Fold one build observation into a ledger row.

    `max` accumulates while `body_hash` holds and restarts when it changes;
    `hist` only ever rises. A row whose function is absent from this build keeps
    its banked numbers - `hist` guarantees nothing is ever lost.
    """
    old = previous.get(mangled) or {}
    old_hash = old.get("hash") or ""
    old_max = old.get("max")
    old_hist = old.get("hist")
    tries = old.get("tries") or 0

    if body_hash and old_hash and body_hash != old_hash:
        tries += 1
        maximum = cur                      # new body: prove it again
    else:
        maximum = cur if old_max is None else max(old_max, cur or 0)

    hist = max(v for v in (old_hist, maximum, cur, 0) if v is not None)

    row = {
        "mangled": mangled,
        "module": module or old.get("module") or "",
        "cls": cls or "",
        "cur": cur,
        "max": maximum,
        "hist": hist,
        "tries": tries,
        "hash": body_hash or old_hash or "",
        "note": note if note is not None else old.get("note", ""),
    }
    row["status"] = status_for(row, flagged=flagged, paired=paired)
    return row


# --------------------------------------------------------------------------
# one-time migration out of match.db
# --------------------------------------------------------------------------

def migrate_from_db(db_path, path=STATE_PATH):
    """Build the ledger from the legacy match.db. Lossless for live state.

    `hist` is seeded from every peak the old schema recorded - the current
    maximum, the weaker-gated `history.best_fuzzy_pct`, and every banked epoch -
    which recovers the ~917 rows whose real peaks the over-wide gate erased.
    """
    import sqlite3

    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    rows = {}

    for rec in con.execute(
        """SELECT s.mangled, t.module, p.fuzzy_pct AS cur, p.struct_class AS cls
           FROM target_functions t
           JOIN symbols s ON s.id = t.sym
           LEFT JOIN pairs p ON p.target_rva = t.rva"""
    ):
        rows[rec["mangled"]] = {
            "mangled": rec["mangled"],
            "module": rec["module"] or "",
            "cls": rec["cls"] or "",
            "cur": rec["cur"],
            "max": None,
            "hist": None,
            "tries": 0,
            "hash": "",
            "note": "",
            "_paired": rec["cur"] is not None,
            "_flagged": False,
        }

    def touch(mangled):
        return rows.setdefault(mangled, {
            "mangled": mangled, "module": "", "cls": "", "cur": None,
            "max": None, "hist": None, "tries": 0, "hash": "", "note": "",
            "_paired": False, "_flagged": False,
        })

    for rec in con.execute(
        "SELECT mangled, max_fuzzy_pct, substr(effective_hash, 1, 12) AS body"
        " FROM source_maxima"
    ):
        row = touch(rec["mangled"])
        row["max"] = rec["max_fuzzy_pct"]
        row["hash"] = rec["body"] or ""

    # hist: the union of every peak the old schema knew about
    for rec in con.execute("SELECT mangled, best_fuzzy_pct FROM history"):
        row = touch(rec["mangled"])
        row["hist"] = max(v for v in (row["hist"], rec["best_fuzzy_pct"], 0)
                          if v is not None)
    for rec in con.execute(
        "SELECT mangled, MAX(max_fuzzy_pct) AS peak FROM source_maxima_epochs"
        " GROUP BY mangled"
    ):
        row = touch(rec["mangled"])
        row["hist"] = max(v for v in (row["hist"], rec["peak"], 0)
                          if v is not None)

    for rec in con.execute("SELECT mangled, n, note FROM attempts"):
        row = touch(rec["mangled"])
        row["tries"] = rec["n"] or 0
        if rec["note"]:
            row["note"] = rec["note"]

    # a flag's cause is the park/block reasoning - it outranks an attempt note
    for rec in con.execute(
        "SELECT mangled, GROUP_CONCAT(cause, ' | ') AS cause FROM flags"
        " GROUP BY mangled"
    ):
        row = touch(rec["mangled"])
        row["_flagged"] = True
        if rec["cause"]:
            row["note"] = rec["cause"]
    con.close()

    for row in rows.values():
        for key in ("max", "hist"):
            if row[key] is None and row["cur"] is not None:
                row[key] = row["cur"]
        if row["hist"] is not None and row["max"] is not None:
            row["hist"] = max(row["hist"], row["max"])
        row["status"] = status_for(row, flagged=row.pop("_flagged"),
                                   paired=row.pop("_paired"))

    return save(rows, path), rows


def export_from_db(db_path, path=STATE_PATH):
    """Project the freshly-regenerated cache into the committed ledger.

    The cache owns the roster, `cur`, `cls`, `max` and the park/attempt notes;
    this function owns `hist`, which it ratchets against the previous ledger so
    a peak can never be lost - not by an ICF fold, not by a reset, not by a
    build in which the function fails to appear at all.
    """
    import sqlite3

    previous = load(path)
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    rows = {}

    for rec in con.execute(
        """SELECT s.mangled, t.module, t.size, t.frameless, u.name AS unit,
                  p.fuzzy_pct AS cur, p.struct_class AS cls
           FROM target_functions t
           JOIN symbols s ON s.id = t.sym
           LEFT JOIN units u ON u.id = t.unit
           LEFT JOIN pairs p ON p.target_rva = t.rva"""
    ):
        rows[rec["mangled"]] = {
            "mangled": rec["mangled"], "module": rec["module"] or "",
            "unit": rec["unit"] or "", "size": rec["size"] or 0,
            "flags": "f" if rec["frameless"] else "",
            "cls": rec["cls"] or "", "cur": rec["cur"], "max": None,
            "tries": 0, "hash": "", "note": "",
            "_paired": rec["cur"] is not None, "_flagged": False,
        }

    def touch(mangled):
        return rows.setdefault(mangled, {
            "mangled": mangled, "module": "", "unit": "", "size": 0,
            "flags": "", "cls": "", "cur": None,
            "max": None, "tries": 0, "hash": "", "note": "",
            "_paired": False, "_flagged": False,
        })

    for rec in con.execute(
        "SELECT mangled, max_fuzzy_pct, effective_hash FROM source_maxima"
    ):
        row = touch(rec["mangled"])
        row["max"] = rec["max_fuzzy_pct"]
        row["hash"] = (rec["effective_hash"] or "").split(".")[0]
    for rec in con.execute("SELECT mangled, n, note FROM attempts"):
        row = touch(rec["mangled"])
        row["tries"] = rec["n"] or 0
        if rec["note"]:
            row["note"] = rec["note"]
    for rec in con.execute(
        "SELECT mangled, GROUP_CONCAT(cause, ' | ') AS cause FROM flags"
        " GROUP BY mangled"
    ):
        row = touch(rec["mangled"])
        row["_flagged"] = True
        if rec["cause"]:
            row["note"] = rec["cause"]
    con.close()

    # rows banked in the ledger but absent from this build keep everything they
    # had; their proven work outlives the build that stopped emitting them.
    for mangled, old in previous.items():
        if mangled not in rows:
            rows[mangled] = dict(old, _paired=False,
                                 _flagged=old.get("status") == "parked")

    for mangled, row in rows.items():
        old = previous.get(mangled, {})
        if row["max"] is None:
            row["max"] = old.get("max") if old.get("max") is not None else row["cur"]
        elif old.get("max") is not None and old.get("hash") == row["hash"]:
            # same body: the ledger owns the peak, so a wiped or reset cache
            # cannot cost us proven work
            row["max"] = max(row["max"], old["max"])
        if not row["note"]:
            row["note"] = old.get("note", "")
        row["hist"] = max(
            v for v in (old.get("hist"), row["max"], row["cur"], 0)
            if v is not None
        )
        row["status"] = status_for(row, flagged=row.pop("_flagged"),
                                   paired=row.pop("_paired"))
    return save(rows, path)


def seed_db_tables(path=STATE_PATH):
    """Reconstruct the cache's persistent tables from the ledger.

    Used when `binaries/match.db` is absent (a fresh clone, or a wiped build
    tree): the committed ledger is the only copy of the campaign's memory, so
    the regen must start from it rather than from nothing.
    """
    rows = load(path)
    history, maxima, attempts, flags = {}, {}, [], []
    for mangled, row in rows.items():
        history[mangled] = (mangled, "", row.get("hist"), row.get("cur"),
                            row.get("cls") or None, "")
        if row.get("max") is not None:
            maxima[mangled] = (
                mangled, row.get("hash") or "", row["max"],
                int(row["max"] >= EXACT), None, row.get("module") or None,
                None, None, None, "ledger", None,
            )
        if row.get("tries"):
            attempts.append((mangled, row["tries"], "", row.get("note") or None))
        if row.get("status") == "parked":
            flags.append((mangled, "SKIP", row.get("note") or "", ""))
    return history, maxima, attempts, flags


def main(argv):
    if len(argv) > 1 and argv[1] == "export":
        db = str(paths.MATCH_DB)
        if len(argv) > 2:
            db = argv[2]
        n = export_from_db(db)
        print(f"[match_state] wrote {n} rows -> {STATE_PATH}")
        return 0
    if len(argv) > 1 and argv[1] == "migrate":
        db = str(paths.DOCS_MATCHING / "match.db")
        if len(argv) > 2:
            db = argv[2]
        n, rows = migrate_from_db(db)
        recovered = sum(1 for r in rows.values()
                        if r["hist"] and r["max"] and r["hist"] > r["max"] + 0.01)
        done = sum(1 for r in rows.values() if r["status"] == "done")
        print(f"[match_state] wrote {n} rows -> {STATE_PATH}")
        print(f"[match_state]   {done} done, {recovered} rows recovered a peak "
              f"the old gate had erased")
        return 0
    print(__doc__)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
