"""match_state - the committed matching ledger, one text row per function.

Replaced the committed `match.db` blob, and then the cache behind it. SQLite
re-serialises pages on write, so git cannot delta it: every matching commit
stored a fresh ~4 MB blob (1,333 of them, ~3.5 GB of history). A flat TSV deltas
per line - ~20 KB per commit - and `git diff` names the functions that moved.

  docs/binary_matching/match_state.tsv    the record; there is no other copy

The derived roster (pairs, per-statement classification, cross-name aliases) is
a pure function of `report.json` + the rich indexes and is rebuilt by
`vostok.derive.roster.regen()` on every build, which hands it to `project`
below. Only the columns that survive a rebuild and cannot be recomputed - hist,
note, tries, and a banked max - are the matching campaign's memory.

Percentage semantics (gruntz naming; see docs in ~/Projects/surv/):

  cur   fuzzy % in THIS build. Noisy under LTCG/ICF - a function can move
        without its source moving.
  max   peak for THIS source body (`hash`). Resets only when `hash` changes,
        because a rewritten body must prove itself again. The campaign goal is
        to drive every `max` to 100, then take one final simultaneous pass.
  hist  all-time peak. NEVER resets. `hist > max` means we scored better once
        and lost it - a worklist row, and the safety net that makes a wrong
        `max` reset harmless.

`hash` is the function's own source body only (12 hex chars). It deliberately
does NOT include module/TU context: the old `effective_hash` folded in the
owning module's headers and the whole owning .cpp, so editing any sibling
function in a TU reset `max` for every function in it. That left 16,659 of
16,661 rows with max == cur - a 16 MB duplicate of a 0.07 MB column. Context
belongs in the diagnosis, not in the gate.
"""

import csv
import os
import sys

from vostok.core import paths

VOSTOK = str(paths.REPO)
STATE_PATH = str(paths.MATCH_STATE)

# Column order is the file format; keep it stable so diffs stay readable.
COLUMNS = [
    "mangled",   # identity (the demangled form is derived, never stored)
    "unit",      # owning TU path, spelled out; a matcher owns a whole TU
    "module",    # logical owner, resolved through unit->module overrides
    "status",    # done | inprogress | blocked | parked
    "cls",       # MATCH | SIZE | QUANTITY | SPLIT  (structure verdict)
    "cur",       # this build
    "max",       # peak for this `hash`
    "hist",      # all-time peak, never resets
    "tries",     # matcher dispatches; a build never bumps it
    "size",      # target byte size - the report headline is byte-weighted
    "flags",     # 'f' = frameless (LTCG-customised leaf; queue skips these)
    "hash",      # 12 hex chars of the function's own source body
    "note",      # what was attempted / why parked or blocked - keep it short
]

EXACT = 99.995  # objdiff reports byte-exact as >= this

HEADER = """\
# vostok matching ledger - generated by vostok.ledger.store. DO NOT hand-edit.
#   one row per target function; the derived roster is rebuilt from report.json
#
#   cur    fuzzy % in this build (noisy under LTCG/ICF)
#   max    peak for THIS source body (`hash`); resets only when `hash` changes.
#          Campaign goal: drive every max to 100.
#   hist   all-time peak; NEVER resets. hist > max = we had it better once.
#   tries  matcher dispatches that included this function (high = hard to match).
#          It moves ONLY when someone runs `vostok ledger tried` - a build that
#          changes the body does NOT bump it.
#   hash   12 hex chars of the function's own source body. Module/TU context is
#          deliberately excluded - it is diagnosis, not a gate.
#   cls    MATCH (statements identical) | SIZE (same count+geometry, bytes
#          differ) | QUANTITY (counts differ) | SPLIT (counts equal, unpairable)
#   status done (max>=100) | inprogress | blocked (something missing) |
#          parked (failed to raise it further)
"""


def _fmt(value):
    """Render a cell: trim floats, blank for None, never emit a tab/newline."""
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.4f}".rstrip("0").rstrip(".")
    return str(value).replace("\t", " ").replace("\n", " ").replace("\r", "")


def _num(text):
    if text in (None, ""):
        return None
    try:
        return float(text)
    except ValueError:
        return None


# Only ever READ now: revisions before 2026-08-16 interned unit paths through
# this legend. `save` no longer writes one - see why there.
UNIT_LEGEND = "# [units] "


def load(path=STATE_PATH):
    """Read the ledger into {mangled: row-dict}.

    Revisions written before 2026-08-16 encode `unit` as an id into a
    `# [units]` legend; they still load, resolved through it. See `save` for
    why new writes spell the path out.
    """
    rows = {}
    if not os.path.exists(path):
        return rows
    units = {}
    with open(path, encoding="utf-8", newline="") as fh:
        body = []
        for line in fh:
            if line.startswith(UNIT_LEGEND):
                ident, _, name = line[len(UNIT_LEGEND):].strip().partition("\t")
                units[ident] = name
            elif not line.startswith("#"):
                body.append(line)
        for rec in csv.DictReader(body, delimiter="\t"):
            mangled = rec.get("mangled")
            if not mangled:
                continue
            for key in ("cur", "max", "hist"):
                rec[key] = _num(rec.get(key))
            rec["tries"] = int(rec["tries"]) if rec.get("tries") else 0
            rec["size"] = int(rec["size"]) if rec.get("size") else 0
            unit = rec.get("unit") or ""
            rec["unit"] = units.get(unit, unit) if units else unit
            rows[mangled] = rec
    return rows


def save(rows, path=STATE_PATH):
    """Write the ledger deterministically: sorted, LF endings, stable columns.

    `unit` holds the TU PATH, not an id. An earlier version interned paths
    through a `# [units]` legend to keep 45 chars out of 19k rows, and that
    interning was a mistake for two reasons:

    * The ids were positions in a sorted list, recomputed on every write, so
      introducing ONE unit that sorts early renumbered every id after it and
      rewrote all 19k rows. A 1,765-row change produced a 21,384-line diff -
      the opposite of the small-diff property this file exists to have.
    * Assigning ids from the file's own history instead would be worse: two
      branches would independently hand the same id to different TUs, and a
      textual merge would take one legend line and silently repoint every row
      that used it. A ledger row must not depend on a cross-reference that a
      merge can resolve wrongly.

    Spelling the path out costs 0.61 MB (5.80 -> 6.41) and buys back both: a row
    is self-contained (so merges are line-local and can't mean the wrong TU),
    and `git diff` names the TU on the changed line instead of an id the
    reader has to resolve against a legend elsewhere in the file. Per-commit
    cost is ~40 bytes on each CHANGED line, which is what actually matters.
    """
    ordered = sorted(rows.values(), key=lambda r: r["mangled"])
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER)
        writer = csv.writer(fh, delimiter="\t", lineterminator="\n")
        writer.writerow(COLUMNS)
        for row in ordered:
            writer.writerow([_fmt(row.get(col)) for col in COLUMNS])
    os.replace(tmp, path)
    return len(ordered)


def status_for(row, flagged=False, paired=True):
    """done > parked > blocked > inprogress, in that precedence."""
    if (row.get("max") or 0) >= EXACT:
        return "done"
    if flagged:
        return "parked"
    if not paired:
        return "blocked"
    return "inprogress"


def project(observations, path=STATE_PATH):
    """Fold this build's observations into the committed ledger. THE build path.

    `vostok.derive` owns the roster columns (unit / module / size / flags), `cur`,
    `cls`, and the hash-scoped `max`; it recomputes all of them from report.json
    and the rich indexes on every build. This function owns everything a build
    must NOT be able to destroy:

      hist    ratcheted here, so a peak survives an ICF fold, a max reset, and a
              build in which the function fails to appear at all
      max     when this build made no hash-scoped observation, the banked peak
              stays - together with the `hash` it belongs to, since a peak and
              the body it was proven on only mean anything as a pair
      note    what was attempted, or why the row is parked
      tries   matcher dispatches; a build never bumps it
      status  done > parked > blocked > inprogress

    An observation is a dict: mangled, unit, module, size, frameless, cls, cur,
    max, hash - `max`/`hash` absent (None/"") when the function has no
    source-backed observation this build.
    """
    previous = load(path)
    rows = {}
    for observation in observations:
        mangled = observation["mangled"]
        old = previous.get(mangled, {})
        rows[mangled] = {
            "mangled": mangled,
            "module": observation["module"] or "",
            "unit": observation["unit"] or "",
            "size": observation["size"] or 0,
            "flags": "f" if observation["frameless"] else "",
            "cls": observation["cls"] or "",
            "cur": observation["cur"],
            "max": observation["max"],
            "hash": observation["hash"] or "",
            "tries": old.get("tries") or 0,
            "note": old.get("note", ""),
            "_paired": observation["cur"] is not None,
            "_flagged": old.get("status") == "parked",
        }

    # rows banked in the ledger but absent from this build keep everything they
    # had; their proven work outlives the build that stopped emitting them.
    for mangled, old in previous.items():
        if mangled not in rows:
            rows[mangled] = dict(old, _paired=False,
                                 _flagged=old.get("status") == "parked")

    for mangled, row in rows.items():
        old = previous.get(mangled, {})
        if row["max"] is None:
            row["max"] = old.get("max") if old.get("max") is not None else row["cur"]
            row["hash"] = row["hash"] or old.get("hash") or ""
        elif old.get("max") is not None and old.get("hash") == row["hash"]:
            # same body: the ledger owns the peak, so a build that scores lower
            # (ICF fold, sibling inline decision) cannot cost us proven work
            row["max"] = max(row["max"], old["max"])
        row["hist"] = max(
            v for v in (old.get("hist"), row["max"], row["cur"], 0) if v is not None
        )
        row["status"] = status_for(row, flagged=row.pop("_flagged"),
                                   paired=row.pop("_paired"))
    return save(rows, path)


def advance(previous, mangled, *, module, cur, cls, body_hash, paired=True,
            flagged=False, note=None):
    """Fold one build observation into a ledger row.

    NOT ON THE BUILD PATH - `project` is. This is the single-row form, kept for a
    report-only writer; note that it bumps `tries` on a body change, which
    `project` does not (there `tries` is a dispatch count nothing derives). Do
    not read it as the live cur/max/hist policy.

    `max` accumulates while `body_hash` holds and restarts when it changes;
    `hist` only ever rises. A row whose function is absent from this build keeps
    its banked numbers - `hist` guarantees nothing is ever lost.
    """
    old = previous.get(mangled) or {}
    old_hash = old.get("hash") or ""
    old_max = old.get("max")
    old_hist = old.get("hist")
    tries = old.get("tries") or 0

    if body_hash and old_hash and body_hash != old_hash:
        tries += 1
        maximum = cur                      # new body: prove it again
    else:
        maximum = cur if old_max is None else max(old_max, cur or 0)

    hist = max(v for v in (old_hist, maximum, cur, 0) if v is not None)

    row = {
        "mangled": mangled,
        "module": module or old.get("module") or "",
        "cls": cls or "",
        "cur": cur,
        "max": maximum,
        "hist": hist,
        "tries": tries,
        "hash": body_hash or old_hash or "",
        "note": note if note is not None else old.get("note", ""),
    }
    row["status"] = status_for(row, flagged=flagged, paired=paired)
    return row


def main(argv):
    """No verbs: the ledger is written by `vostok build` (through `project`) and
    queried with `vostok ledger`. This entry point only explains the format."""
    print(__doc__)
    return 0 if len(argv) > 1 and argv[1] in ("-h", "--help") else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
