// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef VOSTOK_RENDER_FACADE_SOURCES_RENDER_FACADE_ENTRY_POINT_H_INCLUDED
#define VOSTOK_RENDER_FACADE_SOURCES_RENDER_FACADE_ENTRY_POINT_H_INCLUDED
#include <vostok/render/api.h>
#include <vostok/render/core/memory.h>

#endif // #ifndef VOSTOK_RENDER_FACADE_SOURCES_RENDER_FACADE_ENTRY_POINT_H_INCLUDED
