# SPDX-License-Identifier: GPL-3.0-or-later
# Mirror the WSL checkout (where commits and `vostok build` happen) into this native tree:
#
#   sources - check out the WSL branch tip, then apply its uncommitted diff to sources/ and
#             copy its untracked files under sources/. The native tree is a mirror: the
#             previous sync's changes are discarded first, and anything else uncommitted
#             here stops the sync unless -Force.
#   graph   - copy binaries/ninja (vcproj2ninja's graph, regenerated by every `vostok build`)
#             and rewrite Wine's Z:<wsl repo> root to C:\survarium.
#
# Rerun the graph sync after a WSL build whenever a .vcproj or an #include set changed:
# header dependencies are implicit inputs found by the graph's header scan.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\windows\sync.ps1 [-Branch run-fixes] [-SourcesOnly|-GraphOnly]
param([string]$Distro = 'vostok', [string]$WslRepo = '~/vostok', [string]$Branch = '',
      [switch]$SourcesOnly, [switch]$GraphOnly, [switch]$Force)
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\common.ps1"

$wslRepoAbs = Get-WslPath $Distro $WslRepo
$wslShare = "\\wsl.localhost\$Distro" + ($wslRepoAbs -replace '/', '\')
$marker = Join-Path $NativeDir 'sync.state'
function Get-TreeState { (& git -c core.quotepath=off -C $RepoRoot status --porcelain -- sources | Out-String).Trim() }
function Invoke-Git { & git -c safe.directory='*' -C $RepoRoot @args; if ($LASTEXITCODE -ne 0) { throw "git $args failed" } }

if (-not $GraphOnly) {
    if (-not $Branch) { $Branch = (& wsl.exe -d $Distro -- git -C $wslRepoAbs rev-parse --abbrev-ref HEAD | Out-String).Trim() }
    $state = Get-TreeState
    $previous = if (Test-Path $marker) { (Get-Content $marker -Raw).Trim() } else { '' }
    $dirtyOutside = (& git -C $RepoRoot status --porcelain --untracked-files=no | Where-Object { $_ -notmatch ' sources/' })
    if (-not $Force -and (($state -and $state -ne $previous) -or $dirtyOutside)) {
        throw "the native tree has local changes the last sync did not make (git status) - commit them in WSL, or rerun with -Force to discard them"
    }
    Invoke-Git fetch -q wsl $Branch
    Invoke-Git checkout -q -- .
    Invoke-Git clean -qfd -- sources
    Invoke-Git checkout -q -B $Branch FETCH_HEAD

    New-Item -ItemType Directory -Force $NativeDir | Out-Null
    $patch = Join-Path $NativeDir 'wsl_worktree.patch'
    $patchWsl = (& wsl.exe -d $Distro -- wslpath -u ($patch -replace '\\', '/') | Out-String).Trim()
    & wsl.exe -d $Distro -- bash -c "cd '$wslRepoAbs' && git diff HEAD -- sources > '$patchWsl'"
    if ((Get-Item $patch).Length -gt 0) { Invoke-Git apply --whitespace=nowarn $patch }
    $untracked = @(& wsl.exe -d $Distro -- git -C $wslRepoAbs ls-files --others --exclude-standard -- sources)
    foreach ($rel in $untracked) {
        $dst = Join-Path $RepoRoot ($rel -replace '/', '\')
        New-Item -ItemType Directory -Force (Split-Path $dst) | Out-Null
        Copy-Item -LiteralPath (Join-Path $wslShare ($rel -replace '/', '\')) $dst -Force
    }
    Set-Content -Path $marker -Value (Get-TreeState) -Encoding utf8
    $changed = @(Select-String -Path $patch -Pattern '^diff --git').Count
    "sources: $(& git -C $RepoRoot log --oneline -1) + $changed uncommitted file(s), $($untracked.Count) untracked"
}

if (-not $SourcesOnly) {
    $src = Join-Path $wslShare 'binaries\ninja'
    if (-not (Test-Path "$src\build.ninja")) { throw "no graph at $src - run python3 -m vostok build (or vostok.build.ninja_regen) in WSL first" }
    # Wine maps / to Z:; ninja-escaped forms ($:) first. Paths already on c:/survarium/sources stay.
    $win = $wslRepoAbs -replace '/', '\'
    $rewrites = @(
        @("Z`$:$wslRepoAbs", 'C$:/survarium'), @("Z`$:$win", 'C$:\survarium'),
        @("Z:$wslRepoAbs", 'C:/survarium'),    @("Z:$win", 'C:\survarium'))
    $latin1 = [Text.Encoding]::GetEncoding(28591)   # byte-exact round trip whatever the rsp encoding
    New-Item -ItemType Directory -Force "$NinjaDir\rsp" | Out-Null
    $files = @(Get-ChildItem "$src\*.ninja") + @(Get-ChildItem "$src\rsp\*.rsp")
    $written = 0; $leftovers = 0
    foreach ($f in $files) {
        $text = [IO.File]::ReadAllText($f.FullName, $latin1)
        foreach ($r in $rewrites) { $text = $text.Replace($r[0], $r[1]) }
        $leftovers += ([regex]::Matches($text, 'Z\$?:[\\/]')).Count
        $out = Join-Path $NinjaDir $f.FullName.Substring($src.Length + 1)
        # write only what changed: rsp files are implicit inputs, a rewrite would dirty every TU
        if ((Test-Path $out) -and [IO.File]::ReadAllText($out, $latin1) -eq $text) { continue }
        [IO.File]::WriteAllText($out, $text, $latin1); $written++
    }
    "graph: $($files.Count) files, $written rewritten, remaining Z: references: $leftovers"
    if ($leftovers) { Write-Warning "unconverted Wine paths left in the graph - the build will not find those files" }
}
