#!/usr/bin/env python3
"""Roll up the objdiff match report into a human-readable score.

Reads ``binaries/objdiff/report.json`` (regenerated by every ``rebuild.py`` base
delink) and prints an overall line plus a per-module table, all derived from
objdiff's own measures - NOT from the source ``// STATE[..]`` markers (which are
often absent or stale). This is the regression tracker: the same numbers written
into README.md's score block let you diff matching progress across commits
without running anything.

Two precise metrics per module (both are exact sums, ideal for spotting
regressions):
  - functions exact: ``matched_functions`` / ``total_functions`` - functions
    objdiff scores at 100%.
  - code matched: ``matched_code`` / ``total_code`` - bytes fully matched.
The headline also shows objdiff's overall ``fuzzy_match_percent`` (partial
credit included), taken verbatim from the report's top-level measures.

Usage:
    python3 scripts/match_score.py                 # print to stdout
    python3 scripts/match_score.py --write-readme   # refresh README.md block
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "binaries" / "objdiff" / "report.json"
README = REPO / "README.md"

START = "<!-- match-score:start -->"
END = "<!-- match-score:end -->"


def _module_of(unit_name: str) -> str | None:
    """Engine module a unit belongs to, or None for non-``vostok/`` units.

    Unit names look like ``vostok/<module>/<file>``; the module is the second
    path segment (so ``vostok/network_core/x`` is ``network_core``, distinct
    from ``vostok/network/y``).

    Root-level headers are ``vostok/<file>`` (two segments, no module dir) - the
    shared library headers (math, containers, strings, configs, memory) that are
    compiled into many modules. They have no owning module, so bucket them under
    ``shared`` rather than dropping them from every per-module tally (which would
    silently hide header-inlined matches, e.g. ``math::get_relative_matrix`` in
    ``vostok/math_float4x4_inline.h``).
    """
    parts = unit_name.split("/")
    if parts[0] != "vostok":
        return None
    if len(parts) >= 3:
        return parts[1]
    if len(parts) == 2:
        return "shared"
    return None


def _int(v) -> int:
    # objdiff serializes the big code/data counters as strings.
    return int(v) if v is not None else 0


def _pct(num: int, den: int) -> float:
    return 100.0 * num / den if den else 0.0


def collect(report: dict) -> tuple[dict, dict]:
    """Return (overall measures, {module: aggregated measures})."""
    overall = report["measures"]
    mods: dict[str, dict] = {}
    for unit in report.get("units", []):
        mod = _module_of(unit.get("name") or "")
        if mod is None:
            continue
        m = unit.get("measures", {})
        acc = mods.setdefault(
            mod,
            {"units": 0, "total_functions": 0, "matched_functions": 0,
             "total_code": 0, "matched_code": 0, "fuzzy_weighted": 0.0},
        )
        acc["units"] += 1
        acc["total_functions"] += _int(m.get("total_functions"))
        acc["matched_functions"] += _int(m.get("matched_functions"))
        tc = _int(m.get("total_code"))
        acc["total_code"] += tc
        acc["matched_code"] += _int(m.get("matched_code"))
        acc["fuzzy_weighted"] += (m.get("fuzzy_match_percent") or 0.0) * tc
    return overall, mods


def render(overall: dict, mods: dict, delinker_rev: str) -> str:
    funcs = _int(overall.get("matched_functions"))
    tfuncs = _int(overall.get("total_functions"))
    fuzzy = overall.get("fuzzy_match_percent") or 0.0
    today = datetime.date.today().isoformat()

    lines = [
        START,
        "## Match status",
        "",
        "_Auto-generated from `binaries/objdiff/report.json` by "
        "`scripts/match_score.py` - re-run after every re-delink; do not "
        "hand-edit. Diff this block across commits to spot regressions._",
        "",
        f"**Overall: {fuzzy:.2f}% fuzzy &middot; "
        f"{funcs:,} / {tfuncs:,} functions exact "
        f"({_pct(funcs, tfuncs):.2f}%).**",
        "",
        "| Module | Units | Functions exact | Code matched |",
        "|---|--:|--:|--:|",
    ]
    for mod in sorted(mods, key=lambda k: -mods[k]["total_functions"]):
        a = mods[mod]
        fe = f"{a['matched_functions']:,} / {a['total_functions']:,} " \
             f"({_pct(a['matched_functions'], a['total_functions']):.1f}%)"
        cm = f"{_pct(a['matched_code'], a['total_code']):.1f}%"
        lines.append(f"| `{mod}` | {a['units']} | {fe} | {cm} |")
    lines += [
        "",
        f"_Updated {today} &middot; delinker `{delinker_rev}` "
        f"(folded-symbol reconciliation)._",
        END,
    ]
    return "\n".join(lines)


def _delinker_rev() -> str:
    try:
        lock = json.loads((REPO / "flake.lock").read_text())
        rev = lock["nodes"]["vostok-delinker-src"]["locked"]["rev"]
        return rev[:7]
    except (OSError, ValueError, KeyError, TypeError) as e:
        # The rev is cosmetic (README footer), but don't hide a broken
        # flake.lock behind a silent "unknown".
        print(f"[match_score] WARNING: no delinker rev from flake.lock: {e}",
              file=sys.stderr)
        return "unknown"


def write_readme(block: str) -> None:
    text = README.read_text()
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END):]
        README.write_text(pre + block + post)
    else:
        # First install: drop the block right after the intro paragraph (the
        # blank line before the first "## " heading).
        marker = "\n## "
        i = text.index(marker)
        README.write_text(text[:i] + "\n" + block + "\n" + text[i:])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write-readme", action="store_true",
                    help="refresh the score block in README.md")
    args = ap.parse_args()

    try:
        report = json.loads(REPORT.read_text())
    except OSError:
        sys.exit(f"[match_score] {REPORT} not found - run python3 scripts/rebuild.py "
                 "(or generate_delink.py --report-only) first")
    overall, mods = collect(report)
    block = render(overall, mods, _delinker_rev())
    print(block)
    if args.write_readme:
        write_readme(block)
        print(f"\n[match_score] wrote score block to {README}")


if __name__ == "__main__":
    main()
