#!/usr/bin/env python3
"""Roll up the objdiff match report into a human-readable score.

Reads ``binaries/objdiff/report.json`` (regenerated by every ``rebuild.py`` base
delink) and prints an overall line plus a per-module table, all derived from
objdiff's own measures - NOT from the source ``// STATE[..]`` markers (which are
often absent or stale). This is the regression tracker: the same numbers written
into README.md's score block let you diff matching progress across commits
without running anything.

Two precise metrics per module (both are exact sums, ideal for spotting
regressions):
  - functions exact: ``matched_functions`` / ``total_functions`` - functions
    objdiff scores at 100%.
  - code matched: ``matched_code`` / ``total_code`` - bytes fully matched.
The headline also shows objdiff's overall ``fuzzy_match_percent`` (partial
credit included), taken verbatim from the report's top-level measures.

A third, on-demand view (``--max-code``) reads match.db instead of the report:
per module, code-match on BOTH rulers - ``fuzzy`` (partial credit, ~82% - "how
close") and ``exact`` (byte-perfect, ~26% - the README "Code matched") - each with
a source-hash-scoped ``max`` column from ``source_maxima``. Weighted over ALL
target code, so TRGT_ONLY/unpaired functions count as 0% dead weight.

Usage:
    python3 scripts/match_score.py                  # print to stdout
    python3 scripts/match_score.py --write-readme    # refresh README.md block
    python3 scripts/match_score.py --max-code        # code matched vs best-ever
    python3 scripts/match_score.py --max-code --module game_core
"""

from __future__ import annotations

import argparse
import datetime
import json
import sqlite3
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "binaries" / "objdiff" / "report.json"
README = REPO / "README.md"
MATCH_DB = REPO / "binaries" / "match.db"

START = "<!-- match-score:start -->"
END = "<!-- match-score:end -->"


def _module_of(unit_name: str) -> str | None:
    """Engine module a unit belongs to, or None for non-``vostok/`` units.

    Unit names look like ``vostok/<module>/<file>``; the module is the second
    path segment (so ``vostok/network_core/x`` is ``network_core``, distinct
    from ``vostok/network/y``).

    Root-level headers are ``vostok/<file>`` (two segments, no module dir) - the
    shared library headers (math, containers, strings, configs, memory) that are
    compiled into many modules. They have no owning module, so bucket them under
    ``shared`` rather than dropping them from every per-module tally (which would
    silently hide header-inlined matches, e.g. ``math::get_relative_matrix`` in
    ``vostok/math_float4x4_inline.h``).
    """
    parts = unit_name.split("/")
    if parts[0] != "vostok":
        return None
    if len(parts) >= 3:
        return parts[1]
    if len(parts) == 2:
        return "shared"
    return None


def _int(v) -> int:
    # objdiff serializes the big code/data counters as strings.
    return int(v) if v is not None else 0


def _pct(num: int, den: int) -> float:
    return 100.0 * num / den if den else 0.0


def collect(report: dict) -> tuple[dict, dict]:
    """Return (overall measures, {module: aggregated measures})."""
    overall = report["measures"]
    mods: dict[str, dict] = {}
    for unit in report.get("units", []):
        mod = _module_of(unit.get("name") or "")
        if mod is None:
            continue
        m = unit.get("measures", {})
        acc = mods.setdefault(
            mod,
            {"units": 0, "total_functions": 0, "matched_functions": 0,
             "total_code": 0, "matched_code": 0, "fuzzy_weighted": 0.0},
        )
        acc["units"] += 1
        acc["total_functions"] += _int(m.get("total_functions"))
        acc["matched_functions"] += _int(m.get("matched_functions"))
        tc = _int(m.get("total_code"))
        acc["total_code"] += tc
        acc["matched_code"] += _int(m.get("matched_code"))
        acc["fuzzy_weighted"] += (m.get("fuzzy_match_percent") or 0.0) * tc
    return overall, mods


def _md_table(headers: list[str], aligns: str, rows: list[list[str]]) -> list[str]:
    """Render a GitHub markdown table with pipes aligned to column widths, so the
    raw source reads cleanly in an editor (GitHub renders it identically). `aligns`
    is one char per column: 'l' left, 'r' right."""
    widths = [len(h) for h in headers]
    for r in rows:
        for i, c in enumerate(r):
            widths[i] = max(widths[i], len(c))

    def cell(text: str, i: int) -> str:
        return text.rjust(widths[i]) if aligns[i] == "r" else text.ljust(widths[i])

    def row(cells: list[str]) -> str:
        return "| " + " | ".join(cell(c, i) for i, c in enumerate(cells)) + " |"

    sep = []
    for w, a in zip(widths, aligns):
        sep.append("-" * (w - 1) + ":" if a == "r" else ":" + "-" * (w - 1))
    return [row(headers), "| " + " | ".join(sep) + " |", *(row(r) for r in rows)]


# Third-party libraries: real linked target code, but not engine modules we match -
# excluded so the README stays an engine match tracker (sushi). NOT excluded: the
# `vostok` module is the shared engine library (containers/strings/configs/math,
# report.json's "shared"), heavily matched - it stays. An exclude-set, so a NEW
# engine module auto-appears.
_NON_ENGINE = frozenset({
    "boost", "stlport", "bullet", "vorbis", "ogg", "zlib", "opcode",
    "speedtree", "wildmagic", "fastdelegate",
})


def db_module_stats() -> dict[str, dict]:
    """Per-module stats computed ENTIRELY from match.db (report.json NOT consulted):
    total target functions, TU count, current + source-hash-scoped exact-max
    counts, and byte-weighted current + fuzzy-max %. The MAX figures use
    source_maxima and never inherit ordinary history.best_fuzzy_pct. Third-party /
    catch-all modules (`_NON_ENGINE`) are excluded. Returns module -> dict plus an
    'OVERALL' aggregate; {} if the DB is missing/unreadable."""
    try:
        con = sqlite3.connect(MATCH_DB)
    except Exception:
        return {}
    # module -> [n_funcs, exact_cur, exact_max, code, fuzzy_cur_num, fuzzy_max_num]
    agg: dict[str, list[float]] = {}

    def acc(mod: str, size: float, cur: float, maximum: float, exact_max: bool) -> None:
        if mod in _NON_ENGINE:
            return
        a = agg.setdefault(mod, [0, 0, 0, 0.0, 0.0, 0.0])
        a[0] += 1
        a[1] += 1 if cur >= _EXACT else 0
        a[2] += 1 if exact_max else 0
        a[3] += size
        a[4] += cur * size
        a[5] += maximum * size

    try:
        for mod, size, fz, maximum, exact_max in con.execute(
            "SELECT p.module, p.target_size, p.fuzzy_pct, "
            "m.max_fuzzy_pct, m.exact_proven "
            "FROM paired p LEFT JOIN source_maxima m ON m.mangled = p.mangled"
        ):
            fp = fz or 0.0
            acc(
                mod, size or 0, fp, max(fp, maximum or 0.0),
                bool(exact_max) or fp >= _EXACT,
            )
        # target_only (unpaired): 0% now, full size as weight; MAX credits only
        # retained evidence from the same effective-source epoch.
        for mod, size, maximum, exact_max in con.execute(
            "SELECT t.module, t.size, m.max_fuzzy_pct, m.exact_proven "
            "FROM target_only t LEFT JOIN source_maxima m ON m.mangled = t.mangled"
        ):
            acc(mod, size or 0, 0.0, maximum or 0.0, bool(exact_max))
        units = {m: u for m, u in con.execute(
            "SELECT module, COUNT(*) FROM units GROUP BY module")
            if m not in _NON_ENGINE}
    except Exception:
        return {}
    finally:
        con.close()

    out: dict[str, dict] = {}
    tot = [0, 0, 0, 0.0, 0.0, 0.0]
    for mod, a in agg.items():
        out[mod] = {
            "total_funcs": int(a[0]), "units": int(units.get(mod, 0)),
            "exact_cur": int(a[1]), "exact_max": int(a[2]),
            "fuzzy_cur": a[4] / a[3] if a[3] else 0.0,
            "fuzzy_max": a[5] / a[3] if a[3] else 0.0,
        }
        tot = [x + y for x, y in zip(tot, a)]
    out["OVERALL"] = {
        "total_funcs": int(tot[0]), "units": int(sum(units.values())),
        "exact_cur": int(tot[1]), "exact_max": int(tot[2]),
        "fuzzy_cur": tot[4] / tot[3] if tot[3] else 0.0,
        "fuzzy_max": tot[5] / tot[3] if tot[3] else 0.0,
    }
    return out


def render(overall: dict, mods: dict, delinker_rev: str) -> str:
    today = datetime.date.today().isoformat()

    # Everything in the block is derived from match.db (sushi: "calculated through
    # our database entirely, not by using anything from report"). If the DB is
    # unavailable, fall back to report.json with max == current (no churn history).
    db = db_module_stats()
    if not db:
        db = {m: {
            "total_funcs": a["total_functions"], "units": a["units"],
            "exact_cur": a["matched_functions"], "exact_max": a["matched_functions"],
            "fuzzy_cur": (a["fuzzy_weighted"] / a["total_code"]
                          if a["total_code"] else 0.0),
            "fuzzy_max": (a["fuzzy_weighted"] / a["total_code"]
                          if a["total_code"] else 0.0),
        } for m, a in mods.items()}
        db["OVERALL"] = {
            "total_funcs": _int(overall.get("total_functions")),
            "units": sum(a["units"] for a in mods.values()),
            "exact_cur": _int(overall.get("matched_functions")),
            "exact_max": _int(overall.get("matched_functions")),
            "fuzzy_cur": overall.get("fuzzy_match_percent") or 0.0,
            "fuzzy_max": overall.get("fuzzy_match_percent") or 0.0,
        }

    ov = db["OVERALL"]
    funcs, tfuncs = ov["exact_cur"], ov["total_funcs"]
    rows = []
    for mod in sorted((m for m in db if m != "OVERALL"),
                      key=lambda k: -db[k]["total_funcs"]):
        a = db[mod]
        tot = a["total_funcs"]
        exc, exm = a["exact_cur"], a["exact_max"]
        fzc, fzm = a["fuzzy_cur"], a["fuzzy_max"]
        rows.append([
            f"`{mod}`",
            f"{a['units']}",
            f"{exc:,} / {tot:,} ({_pct(exc, tot):.1f}%)",
            f"{exm:,} / {tot:,} ({_pct(exm, tot):.1f}%)",
            f"{fzc:.1f}%",
            f"{fzm:.1f}%",
        ])
    table = _md_table(
        ["Module", "Units", "Functions exact", "Functions exact-max",
         "Fuzzy", "Fuzzy-max"],
        "lrrrrr",
        rows,
    )

    lines = [
        START,
        "## Match status",
        "",
        "_Auto-generated from `docs/binary_matching/match.db` - refreshed by "
        "`rebuild.py` at the end of every build; do not hand-edit. Diff this block "
        "across commits to spot regressions._",
        "",
        f"**Overall: {funcs:,} / {tfuncs:,} functions exact "
        f"({_pct(funcs, tfuncs):.2f}%) &middot; "
        f"{ov['exact_max']:,} / {tfuncs:,} functions exact-max "
        f"({_pct(ov['exact_max'], tfuncs):.2f}%) &middot; "
        f"{ov['fuzzy_cur']:.2f}% fuzzy &middot; "
        f"{ov['fuzzy_max']:.2f}% fuzzy-max.**",
        "",
        "_All figures come from `match.db` over every target function (paired plus "
        "inlined/folded `target_only`). **Functions exact** and **Fuzzy** describe "
        "the current build. **Exact-max** and **Fuzzy-max** retain only observations "
        "from the same effective-source/compiler-context hash in `source_maxima`; "
        "ordinary `history.best_fuzzy_pct` observations are not promoted to MAX. "
        "Exact-max requires a byte-exact observation in the current source epoch. "
        "Byte-weighted code view: `scripts/match_score.py --max-code`._",
        "",
        *table,
    ]
    lines += [
        "",
        f"_Updated {today} &middot; delinker `{delinker_rev}` "
        f"(folded-symbol reconciliation)._",
        END,
    ]
    return "\n".join(lines)


# a function is byte-exact when objdiff scores it at 100%; allow float slop
_EXACT = 99.995


def code_max(module: str | None = None) -> list[tuple]:
    """Per-module code match on BOTH rulers, each current vs source-scoped MAX.

    Code-weighted over ALL target code: each target function contributes its
    target_size to the denominator, so a TRGT_ONLY/unpaired function is 0%-matched
    dead weight (exactly like objdiff's total_code). Two rulers:
      - fuzzy  : partial credit - a function adds (fuzzy% * size). The "how close"
                 number (~82% for game_core; objdiff's weighted match).
      - exact  : byte-perfect only - a function adds its full size iff fuzzy==100,
                 else 0. The README's "Code matched" (~26%).
    The max columns use source_maxima. They survive compiler-state churn within
    one effective-source epoch and reset when that epoch changes.

    Everything is already in match.db (paired.target_size + target_only.size +
    source_maxima). Returns rows of
    (module, total_code, fuzzy_cur, fuzzy_max, exact_cur, exact_max) sorted by
    code size, with a trailing OVERALL row.
    """
    con = sqlite3.connect(MATCH_DB)
    # module -> [total, fuzzy_cur_num, fuzzy_max_num, exact_cur, exact_max]
    agg: dict[str, list[float]] = {}

    def add(
        mod: str | None, size: int, cur_fz: float, max_fz: float, exact_max: bool
    ) -> None:
        if mod is None:
            return
        a = agg.setdefault(mod, [0.0, 0.0, 0.0, 0.0, 0.0])
        a[0] += size
        a[1] += cur_fz * size
        a[2] += max_fz * size
        a[3] += size if cur_fz >= _EXACT else 0
        a[4] += size if exact_max else 0

    for mod, size, fuzzy, maximum, exact_max in con.execute(
        "SELECT p.module, p.target_size, p.fuzzy_pct, "
        "m.max_fuzzy_pct, m.exact_proven "
        "FROM paired p LEFT JOIN source_maxima m ON m.mangled = p.mangled"
    ):
        fp = fuzzy or 0.0
        add(
            mod, size or 0, fp, max(fp, maximum or 0.0),
            bool(exact_max) or fp >= _EXACT,
        )
    # target-only (no base symbol): 0% now, full size as weight; MAX credits
    # retained same-epoch evidence only.
    for mod, size, maximum, exact_max in con.execute(
        "SELECT t.module, t.size, m.max_fuzzy_pct, m.exact_proven "
        "FROM target_only t LEFT JOIN source_maxima m ON m.mangled = t.mangled"
    ):
        add(mod, size or 0, 0.0, maximum or 0.0, bool(exact_max))
    con.close()

    if module:
        agg = {m: v for m, v in agg.items() if m == module}
    out, tot = [], [0.0, 0.0, 0.0, 0.0, 0.0]
    for mod, a in agg.items():
        t = a[0]
        out.append((mod, int(t), a[1] / t if t else 0, a[2] / t if t else 0,
                    _pct(a[3], t), _pct(a[4], t)))
        tot = [x + y for x, y in zip(tot, a)]
    out.sort(key=lambda r: -r[1])
    t = tot[0]
    out.append(("OVERALL", int(t), tot[1] / t if t else 0, tot[2] / t if t else 0,
                _pct(tot[3], t), _pct(tot[4], t)))
    return out


def render_code_max(rows: list[tuple]) -> str:
    lines = [
        "Code match  (match.db, code-weighted over ALL target code incl. "
        "TRGT_ONLY@0%; max = effective-source-hash scoped)",
        "  fuzzy = partial credit (how close) | exact = byte-perfect "
        "(README 'Code matched')",
        f"{'module':<14}{'code bytes':>12}{'fuzzy':>9}{'fuzzy-max':>11}"
        f"{'exact':>9}{'exact-max':>11}",
    ]
    for mod, tc, fz, fzm, ex, exm in rows:
        lines.append(f"{mod:<14}{tc:>12,}{fz:>8.1f}%{fzm:>10.1f}%"
                     f"{ex:>8.1f}%{exm:>10.1f}%")
    return "\n".join(lines)


def _delinker_rev() -> str:
    try:
        lock = json.loads((REPO / "flake.lock").read_text())
        rev = lock["nodes"]["vostok-delinker-src"]["locked"]["rev"]
        return rev[:7]
    except Exception:
        return "unknown"


def write_readme(block: str) -> None:
    text = README.read_text()
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END):]
        README.write_text(pre + block + post)
    else:
        # First install: drop the block right after the intro paragraph (the
        # blank line before the first "## " heading).
        marker = "\n## "
        i = text.index(marker)
        README.write_text(text[:i] + "\n" + block + "\n" + text[i:])


def regen_readme() -> str:
    """Refresh README.md's score block from the current report.json and return the
    rendered block (callable with no args). rebuild.py calls this at the end of every
    build so the README regression tracker stays current alongside match.db;
    `--write-readme` is the same path from the CLI."""
    report = json.loads(REPORT.read_text())
    overall, mods = collect(report)
    block = render(overall, mods, _delinker_rev())
    write_readme(block)
    return block


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write-readme", action="store_true",
                    help="refresh the score block in README.md")
    ap.add_argument("--max-code", action="store_true",
                    help="print per-module 'code matched' vs 'max code matched' "
                         "(best-ever, churn-immune) from match.db")
    ap.add_argument("--module", help="restrict --max-code to one module")
    args = ap.parse_args()

    if args.max_code:
        print(render_code_max(code_max(args.module)))
        return

    if args.write_readme:
        block = regen_readme()
        print(block)
        print(f"\n[match_score] wrote score block to {README}")
    else:
        report = json.loads(REPORT.read_text())
        overall, mods = collect(report)
        block = render(overall, mods, _delinker_rev())
        print(block)


if __name__ == "__main__":
    main()
