#ifndef VOSTOK_RENDER_FACADE_DEBUG_RENDERER_H_INCLUDED
#define VOSTOK_RENDER_FACADE_DEBUG_RENDERER_H_INCLUDED

#include <vostok/render/facade/sources/debug_renderer.h>

#endif // #ifndef VOSTOK_RENDER_FACADE_DEBUG_RENDERER_H_INCLUDED
