#ifndef VOSTOK_RENDER_FACADE_SCENE_RENDERER_H_INCLUDED
#define VOSTOK_RENDER_FACADE_SCENE_RENDERER_H_INCLUDED

#include <vostok/render/facade/sources/scene_renderer.h>

#endif // #ifndef VOSTOK_RENDER_FACADE_SCENE_RENDERER_H_INCLUDED
