# SPDX-License-Identifier: GPL-3.0-or-later

"""Source-and-diff-scoped reviews for the datum-use zero gate."""

from __future__ import annotations

import csv
import json
from pathlib import Path

from vostok.core import paths
from vostok.core.tsv import write_if_changed


HEADER = (
    "# Codex wall reviews - generated by `vostok data review`; do not hand-edit.\n"
    "# function\tsrc_hash\tdiff_hash\tstatus\twall_class\tevidence\n"
)
STATUSES = ("open", "bounded", "exact")
TERMINAL_STATUSES = frozenset(("bounded", "exact"))
CLASSES = ("referent", "inline", "cfg", "regalloc", "masked", "other")
FIELDS = (
    "function", "src_hash", "diff_hash", "status", "wall_class", "evidence",
)


def load(path: Path | None = None) -> dict[str, dict[str, str]]:
    source_path = path or paths.CODEX_WALL_REVIEWS
    if not source_path.is_file():
        return {}
    rows: dict[str, dict[str, str]] = {}
    with source_path.open(newline="", encoding="utf-8") as source:
        reader = csv.DictReader(
            (line for line in source if not line.startswith("#")),
            delimiter="\t",
            fieldnames=FIELDS,
        )
        for line_number, row in enumerate(reader, 1):
            if not all(row.get(field) for field in FIELDS):
                raise ValueError(
                    f"{source_path}: malformed review row {line_number}"
                )
            if row["status"] not in STATUSES:
                raise ValueError(
                    f"{source_path}: unsupported status {row['status']!r}"
                )
            if row["wall_class"] not in CLASSES:
                raise ValueError(
                    f"{source_path}: unsupported class {row['wall_class']!r}"
                )
            if row["function"] in rows:
                raise ValueError(
                    f"{source_path}: duplicate review for {row['function']}"
                )
            rows[row["function"]] = row
    return rows


def render(rows: dict[str, dict[str, str]]) -> str:
    lines = [HEADER]
    for function, row in sorted(rows.items()):
        evidence = row["evidence"].replace("\t", " ").replace("\n", " ")
        lines.append(
            f"{function}\t{row['src_hash']}\t{row['diff_hash']}\t"
            f"{row['status']}\t{row['wall_class']}\t{evidence}\n"
        )
    return "".join(lines)


def matches(
    review: dict[str, str] | None,
    source_hash: str,
    diff_hash: str,
) -> bool:
    return bool(
        review
        and review["status"] in TERMINAL_STATUSES
        and review["src_hash"] == source_hash
        and review["diff_hash"] == diff_hash
    )


def _function_rows() -> list[dict[str, str]]:
    if not paths.DATA_MODULE_RELOC_REPORT.is_file():
        raise RuntimeError(
            "no all-module datum report; run `python3 -m vostok data "
            "module-relocs all`"
        )
    report = json.loads(
        paths.DATA_MODULE_RELOC_REPORT.read_text(encoding="utf-8")
    )
    result = []
    for module in sorted(report.get("modules", {})):
        path = paths.data_module_function_data(module)
        with path.open(newline="", encoding="utf-8") as source:
            for row in csv.DictReader(source, delimiter="\t"):
                result.append({"module": module, **row})
    return result


def _locate(pattern: str) -> dict[str, str]:
    rows = _function_rows()
    exact = [row for row in rows if row["function"] == pattern]
    if len(exact) == 1:
        return exact[0]
    needle = pattern.casefold()
    matches_rows = [
        row for row in rows
        if needle in "\t".join((
            row["module"], row["unit"], row["function"],
            row["target_function_rvas"],
        )).casefold()
    ]
    if len(matches_rows) != 1:
        choices = "\n".join(
            f"  {row['module']}: {row['function']}"
            for row in matches_rows[:12]
        )
        suffix = f"\n{choices}" if choices else ""
        raise ValueError(
            f"review target {pattern!r} matched {len(matches_rows)} rows{suffix}"
        )
    return matches_rows[0]


def list_reviews() -> int:
    rows = load()
    current_rows = {row["function"]: row for row in _function_rows()}
    current = 0
    for function, review in sorted(rows.items()):
        row = current_rows.get(function)
        fresh = bool(
            row
            and review["src_hash"] == row["source_hash"]
            and review["diff_hash"] == row["diff_hash"]
        )
        current += int(fresh)
        print(
            f"  {(row or {}).get('target_function_rvas', '-'):>12} "
            f"{'current' if fresh else 'STALE':7} {review['status']:7} "
            f"{review['wall_class']:8} {function} - {review['evidence']}"
        )
    print(f"[reviews] {current} current, {len(rows) - current} stale")
    return 0


def record(
    pattern: str,
    status: str,
    wall_class: str,
    evidence: str,
) -> int:
    row = _locate(pattern)
    if row["source_hash"] in {"", "-"}:
        raise ValueError(
            f"{row['function']} has no fresh per-function source hash"
        )
    if status == "exact" and row["resolution"] not in {
        "EXACT", "CURRENT_EXACT", "HASH_MAX_EXACT",
    }:
        raise ValueError(
            "exact review requires current or hash-scoped 100% byte proof"
        )
    rows = load()
    rows[row["function"]] = {
        "function": row["function"],
        "src_hash": row["source_hash"],
        "diff_hash": row["diff_hash"],
        "status": status,
        "wall_class": wall_class,
        "evidence": evidence,
    }
    write_if_changed(paths.CODEX_WALL_REVIEWS, render(rows))
    print(
        f"[reviews] {row['target_function_rvas']} {status} {wall_class} "
        f"at {row['source_hash']}:{row['diff_hash']}"
    )
    return 0


def check() -> int:
    load()
    return 0
